package com.wtfrepo.backend.shared.web;

public enum ErrorCode {
  VALIDATION_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  RESOURCE_NOT_FOUND,
  CONFLICT,
  RATE_LIMITED,
  VOTE_INVALID_WINNER,
  INSUFFICIENT_BUG,
  BATTLE_NOT_FOUND,
  VOTE_DUPLICATE,
  BATTLE_EXPIRED,
  SETTLEMENT_IN_PROGRESS,
  ARENA_NO_MATCH,
  ARENA_POOL_EMPTY,
  BET_INVALID_DIRECTION,
  BET_AMOUNT_TOO_LOW,
  BET_IPO_LOCKED,
  BET_CUTOFF_PASSED,
  BET_POOL_NOT_AVAILABLE,
  IDEMPOTENCY_CONFLICT,
  INTERNAL_ERROR
}
