package com.wtfrepo.backend.arena.application.support;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import com.wtfrepo.backend.shared.policy.ArenaRuntimePolicyPort;
import org.springframework.stereotype.Component;

/**
 * Validates and issues stateless signed battle id generated by duel endpoint.
 *
 * <p>Format: {@code bat_{base64url(payload)}_{hmacHex}} payload:
 * {@code left|right|issuedAtEpochSeconds}
 */
@Component
public class ArenaBattleIdVerifier {

  private final ArenaContractProperties contractProperties;
  private final ArenaRuntimePolicyPort arenaRuntimePolicyPort;

  public ArenaBattleIdVerifier(
      ArenaContractProperties contractProperties, ArenaRuntimePolicyPort arenaRuntimePolicyPort) {
    this.contractProperties = contractProperties;
    this.arenaRuntimePolicyPort = arenaRuntimePolicyPort;
  }

  public String issue(String leftSpecimenId, String rightSpecimenId) {
    return issue(leftSpecimenId, rightSpecimenId, Instant.now());
  }

  public String issue(String leftSpecimenId, String rightSpecimenId, Instant issuedAt) {
    String payload = leftSpecimenId + "|" + rightSpecimenId + "|" + issuedAt.getEpochSecond();
    String encodedPayload =
        Base64.getUrlEncoder().withoutPadding().encodeToString(payload.getBytes(StandardCharsets.UTF_8));
    return ArenaConstants.Battle.ID_PREFIX + encodedPayload + "_" + sign(encodedPayload);
  }

  public VerifiedBattle verify(String battleId) {
    if (battleId == null || !battleId.startsWith(ArenaConstants.Battle.ID_PREFIX)) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }

    String raw = battleId.substring(ArenaConstants.Battle.ID_PREFIX.length());
    int separator = raw.lastIndexOf('_');
    if (separator <= 0 || separator >= raw.length() - 1) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }

    String encodedPayload = raw.substring(0, separator);
    String providedSignature = raw.substring(separator + 1);
    String expectedSignature = sign(encodedPayload);
    if (!MessageDigest.isEqual(
        providedSignature.getBytes(StandardCharsets.UTF_8),
        expectedSignature.getBytes(StandardCharsets.UTF_8))) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }

    String payload =
        new String(Base64.getUrlDecoder().decode(encodedPayload), StandardCharsets.UTF_8);
    String[] parts = payload.split("\\|");
    if (parts.length != 3) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }

    long issuedAtEpoch;
    try {
      issuedAtEpoch = Long.parseLong(parts[2]);
    } catch (NumberFormatException ex) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }

    Instant issuedAt = Instant.ofEpochSecond(issuedAtEpoch);
    Duration ttl = arenaRuntimePolicyPort.currentArenaRuntimePolicy().battleTtl();
    if (issuedAt.plus(ttl).isBefore(Instant.now())) {
      throw ArenaExceptions.battleExpired(ArenaConstants.Message.BATTLE_EXPIRED);
    }

    return new VerifiedBattle(parts[0], parts[1], issuedAt);
  }

  private String sign(String encodedPayload) {
    try {
      Mac mac = Mac.getInstance("HmacSHA256");
      mac.init(
          new SecretKeySpec(
              contractProperties.getBattleIdSecret().getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
      byte[] signature = mac.doFinal(encodedPayload.getBytes(StandardCharsets.UTF_8));
      StringBuilder builder = new StringBuilder(signature.length * 2);
      for (byte value : signature) {
        builder.append(String.format("%02x", value));
      }
      return builder.toString();
    } catch (Exception ex) {
      throw ArenaExceptions.battleNotFound(ArenaConstants.Message.BATTLE_NOT_FOUND);
    }
  }

  public record VerifiedBattle(String leftSpecimenId, String rightSpecimenId, Instant issuedAt) {}
}
